// Generated by CoffeeScript 1.6.3
var Actions;

Actions = (function() {
  /*
  */

  function Actions() {
    this._source = [];
  }

  /*
  */


  Actions.prototype.push = function(event) {
    return this._source.push(event);
  };

  /*
  */


  Actions.prototype.unshift = function(event) {
    return this._source.push(event);
  };

  /*
  */


  Actions.prototype.removeAt = function(index) {
    return this._source.splice(index, 1);
  };

  return Actions;

})();

module.exports = Actions;
