// Generated by CoffeeScript 1.6.3
var express;

express = require("express");

exports.require = ["server"];

exports.plugin = function(server) {
  return server.use(express["static"](__dirname + "/../../../browser"));
};
