// Generated by CoffeeScript 1.6.3
var plugin;

plugin = require("plugin");

module.exports = function(params) {
  return plugin().params(params).require(__dirname + "/plugins").load(function() {});
};
