// Generated by CoffeeScript 1.6.3
var LayoutView, mojo, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

mojo = require("mojojs");

LayoutView = (function(_super) {
  __extends(LayoutView, _super);

  function LayoutView() {
    _ref = LayoutView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  LayoutView.prototype.paper = require("./layout.pc");

  return LayoutView;

})(mojo.View);

module.exports = LayoutView;
