// Generated by CoffeeScript 1.6.3
var BaseListener,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseListener = (function(_super) {
  __extends(BaseListener, _super);

  /*
  */


  function BaseListener() {
    BaseListener.__super__.constructor.call(this);
  }

  /*
  */


  BaseListener.prototype.start = function() {};

  /*
  */


  BaseListener.prototype.stop = function() {};

  return BaseListener;

})(require("events").EventEmitter);

module.exports = BaseListener;
