// Generated by CoffeeScript 1.6.3
var DomListener, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DomListener = (function(_super) {
  __extends(DomListener, _super);

  function DomListener() {
    this._onEvent = __bind(this._onEvent, this);
    _ref = DomListener.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  DomListener.prototype.start = function() {
    var event, events, _i, _len, _results;
    console.log("start DOM2 listener");
    events = ["mousedown"];
    console.log(events);
    _results = [];
    for (_i = 0, _len = events.length; _i < _len; _i++) {
      event = events[_i];
      _results.push(document.body.addEventListener(event, this._onEvent, true));
    }
    return _results;
  };

  /*
  */


  DomListener.prototype.stop = function() {};

  /*
  */


  DomListener.prototype._onEvent = function(event) {
    return console.log(event.type, event.target);
  };

  return DomListener;

})(require("./base"));

module.exports = function() {
  return new DomListener();
};
