// Generated by CoffeeScript 1.6.3
var HttpListener, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

HttpListener = (function(_super) {
  __extends(HttpListener, _super);

  function HttpListener() {
    _ref = HttpListener.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  HttpListener.prototype.start = function() {
    return console.log("start HTTP listener");
  };

  /*
  */


  HttpListener.prototype.stop = function() {};

  return HttpListener;

})(require("./base"));

module.exports = function() {
  return new HttpListener();
};
