// Generated by CoffeeScript 1.6.3
module.exports = {
  group: require("./group"),
  http: require("./http"),
  dom: require("./dom")
};

module.exports.all = function() {
  return module.exports.group([module.exports.http(), module.exports.dom()]);
};
