// Generated by CoffeeScript 1.6.3
var Storage, store,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

store = require("store");

Storage = (function() {
  /*
  */

  function Storage(_recorder) {
    this._recorder = _recorder;
    this.save = __bind(this.save, this);
    this._load();
  }

  /*
  */


  Storage.prototype.save = function(name, callback) {
    return store.set("actions", this._recorder.runners.toJSON());
  };

  /*
  */


  Storage.prototype.autoSave = function() {
    return this._recorder.on("update", this.save);
  };

  /*
  */


  Storage.prototype._load = function(callback) {
    if (callback == null) {
      callback = function() {};
    }
    return this._recorder.runners.fromJSON(store.get("actions") || {});
  };

  return Storage;

})();

module.exports = Storage;
