// Generated by CoffeeScript 1.6.3
var Recap, Recorder, Storage, listeners;

listeners = require("./listeners");

Recorder = require("./recorder");

Storage = require("./storage/local");

Recap = (function() {
  /*
  */

  function Recap() {
    this._recorder = new Recorder(listeners.all());
    this._storage = new Storage(this._recorder);
  }

  /*
  */


  Recap.prototype.help = function() {
    return console.log(["start() - starts recording actions", "stop()  - stops recording actions"].join("\n"));
  };

  /*
   starts recording actions
  */


  Recap.prototype.start = function(name, description) {
    if (!name) {
      throw new Error("name must be provided");
    }
    console.log("recording user interactions");
    return this.current = this._recorder.start(name);
  };

  /*
  */


  Recap.prototype.clear = function() {
    this._recorder.clear();
    return this;
  };

  /*
  */


  Recap.prototype.remove = function(name) {
    this._recorder.remove(name);
    return this;
  };

  /*
   stops recording actions
  */


  Recap.prototype.stop = function() {
    this._recorder.stop();
    return this;
  };

  /*
  */


  Recap.prototype.saved = function() {
    return this._recorder.runners.toJSON();
  };

  /*
  */


  Recap.prototype.autoSave = function() {
    this._storage.autoSave();
    return true;
  };

  /*
  */


  Recap.prototype.save = function() {
    this._storage.save();
    return true;
  };

  return Recap;

})();

window.recap = new Recap();

window.recap.help();
