// Generated by CoffeeScript 1.6.3
var ActionRunner, GroupRunner, flatstack;

flatstack = require("flatstack");

ActionRunner = require("./action");

GroupRunner = (function() {
  /*
  */

  function GroupRunner(runners, name) {
    this.runners = runners;
    this.name = name;
    this.actions = [];
  }

  /*
  */


  GroupRunner.prototype.fromJSON = function(data) {
    this.actions = data.actions;
    this.description = data.description;
    return this.name = data.name;
  };

  /*
  */


  GroupRunner.prototype.toJSON = function() {
    return {
      actions: this.actions,
      description: this.description,
      name: name
    };
  };

  /*
  */


  GroupRunner.prototype.start = function(next) {
    var q;
    if (next == null) {
      next = function() {};
    }
    console.log("%c run %s", "color:#FF00FF;", this.name);
    q = flatstack();
    this.actions.forEach(function(action) {
      return q.push(function(next) {
        return new ActionRunner(this, action).start(next);
      });
    });
    q.push(function() {
      return next();
    });
    return this;
  };

  return GroupRunner;

})();

module.exports = GroupRunner;
