// Generated by CoffeeScript 1.6.3
var ActionRunner, type;

type = require("type-component");

ActionRunner = (function() {
  /*
  */

  function ActionRunner(runner, _action) {
    this.runner = runner;
    this._action = _action;
  }

  /*
  */


  ActionRunner.prototype.start = function(next) {
    var findElement, method, xpath;
    if (next == null) {
      next = function() {};
    }
    if (type(this._action) === "string") {
      return this.runner.runners.get(this._action).start(next);
    }
    method = this._action.type;
    xpath = this._action.data.xpath;
    console.log("%c %s %s", "color:#FF00FF;", method, xpath);
    findElement = function() {
      var $e;
      $e = $(document.body).xpath(xpath);
      if (!$e.length) {
        return setTimeout(findElement, 500);
      }
      $e[method].call($e);
      return next();
    };
    return findElement();
  };

  return ActionRunner;

})();

module.exports = ActionRunner;
