// Generated by CoffeeScript 1.6.3
var ElementRunner, type;

type = require("type-component");

ElementRunner = (function() {
  /*
  */

  function ElementRunner(runner, _event) {
    this.runner = runner;
    this._event = _event;
  }

  /*
  */


  ElementRunner.prototype.start = function(callback) {};

  return ElementRunner;

})();

module.exports = ElementRunner;
