// Generated by CoffeeScript 1.6.3
var GroupRunner, async;

async = require("async");

GroupRunner = (function() {
  /*
  */

  function GroupRunner(_runners, name) {
    this._runners = _runners;
    this.name = name;
    this.actions = [];
  }

  /*
  */


  GroupRunner.prototype.fromJSON = function(data) {
    this.actions = data.actions;
    this.description = data.description;
    return this.name = data.name;
  };

  /*
  */


  GroupRunner.prototype.toJSON = function() {
    return {
      actions: this.actions,
      description: this.description,
      name: name
    };
  };

  /*
  */


  GroupRunner.prototype.start = function() {
    console.log("start %s", this.name);
    console.log($(document.body).xpath(this.actions[0].data.xpath));
    $(document.body).xpath(this.actions[0].data.xpath).click();
    return this;
  };

  return GroupRunner;

})();

module.exports = Runner;
