// Generated by CoffeeScript 1.6.3
var ActionsRunner, Runners;

ActionsRunner = require("./actions");

Runners = (function() {
  /*
  */

  function Runners() {
    this.clear();
  }

  /*
  */


  Runners.prototype.get = function(name) {
    var _ref;
    return (_ref = this._runners[name]) != null ? _ref : (this._runners[name] = new ActionsRunner(this, name));
  };

  /*
  */


  Runners.prototype.remove = function(name) {
    return delete this._runners[ame];
  };

  /*
  */


  Runners.prototype.clear = function() {
    return this._runners = {};
  };

  /*
  */


  Runners.prototype.toJSON = function() {
    var data, name;
    data = {};
    for (name in this._runners) {
      data[name] = this._runners[name].toJSON();
    }
    return data;
  };

  /*
  */


  Runners.prototype.fromJSON = function(runners) {
    var name, r, _results;
    _results = [];
    for (name in runners) {
      this._runners[name] = r = new ActionsRunner(this, name);
      _results.push(r.fromJSON(runners[name]));
    }
    return _results;
  };

  return Runners;

})();

module.exports = Runners;
