// Generated by CoffeeScript 1.6.3
var bindable, pc, pcv;

pc = require("paperclip");

pcv = require("paperclip-view");

bindable = require("bindable");

exports.plugin = function() {
  var components;
  components = new bindable.Object({
    mainLayout: require("./views/layout")
  });
  pc.use(pcv(components));
  return components;
};
