// Generated by CoffeeScript 1.6.3
var BookmarkletView, fs, mojo, pc, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

mojo = require("mojojs");

pc = require("paperclip");

fs = require("fs");

BookmarkletView = (function(_super) {
  __extends(BookmarkletView, _super);

  function BookmarkletView() {
    _ref = BookmarkletView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  BookmarkletView.prototype.paper = require("./bookmarklet.pc");

  return BookmarkletView;

})(mojo.View);

module.exports = BookmarkletView;
