// Generated by CoffeeScript 1.6.3
var BookmarkletView;

BookmarkletView = require("./bookmarklet");

exports.require = ["server", "config", "view.components"];

exports.plugin = function(server, config) {
  console.log("go to /bookmarklet and run it in any browser to start recap");
  return server.get("/bookmarklet", function(req, res) {
    var view;
    view = new BookmarkletView({
      httpPort: config.port
    });
    return view.render(function() {
      return res.send(view.section.toString());
    });
  });
};
