// Generated by CoffeeScript 1.6.3
var flatten, xpgen;

xpgen = require("xpgen");

flatten = require("flatten");

/*
1. find all the available xpaths
2.
*/


module.exports = function(element) {
  var xpaths;
  if (!element || element.nodeName === "BODY") {
    return [];
  }
  xpaths = [];
  xpaths = xpaths.concat(this._xpathsByAttribs(element));
  return xpaths = xpaths.concat(this._xpathsByIndex(element));
};

({
  /*
  */

  _xpathsByAttribs: function(element) {
    var attribute, name, possibilities, value, xpaths, _i, _len, _ref, _results;
    xpaths = [];
    possibilities = [];
    _ref = element.attributes;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      attribute = _ref[_i];
      value = attribute.value;
      name = attribute.name;
      _results.push(xpaths = xpaths.concat(this._xpathsByAttrib(element, name, value)));
    }
    return _results;
  },
  /*
  */

  _xpathsByAttrib: function(element, name, value) {
    var valueParts;
    return valueParts = value.split(" ");
  },
  /*
  */

  _xpathsByIndex: function(element) {
    return xpgen().element(element.nodeName).index(element.parentNode.childNodes.indexOf(element));
  }
});
